In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [13]:
raw_mail_data = pd.read_csv("spam.csv",encoding='latin1')

In [49]:
raw_mail_data.head()

  Prediction                                              Mails
0        ham  Go until jurong point, crazy.. Available only ...
1        ham                      Ok lar... Joking wif u oni...
2       spam  Free entry in 2 a wkly comp to win FA Cup fina...
3        ham  U dun say so early hor... U c already then say...
4        ham  Nah I don't think he goes to usf, he lives aro...

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score

In [53]:
raw_mail_data.isnull().sum()

Prediction    0
Mails         0
dtype: int64

In [55]:
df = raw_mail_data.where((pd.notnull(raw_mail_data)), '')

In [57]:
df.isnull().sum()

Prediction    0
Mails         0
dtype: int64

In [59]:
df.shape

(5572, 2)

In [61]:
# Supervised -> target class
# Unsupervised -> clustering problem

# Label encoding

In [63]:
df['Prediction'] = df['Prediction'].map({'spam': 0, 'ham': 1})

In [65]:
df.head()

   Prediction                                              Mails
0           1  Go until jurong point, crazy.. Available only ...
1           1                      Ok lar... Joking wif u oni...
2           0  Free entry in 2 a wkly comp to win FA Cup fina...
3           1  U dun say so early hor... U c already then say...
4           1  Nah I don't think he goes to usf, he lives aro...

In [67]:
# loc function

In [69]:
df.loc[df['Prediction'] == 'spam', 'Prediction',] = 0
df.loc[df['Prediction'] == 'ham', 'Prediction',] = 1

In [71]:
df.head()

   Prediction                                              Mails
0           1  Go until jurong point, crazy.. Available only ...
1           1                      Ok lar... Joking wif u oni...
2           0  Free entry in 2 a wkly comp to win FA Cup fina...
3           1  U dun say so early hor... U c already then say...
4           1  Nah I don't think he goes to usf, he lives aro...

In [77]:
X = df['Mails']
Y = df['Prediction']

In [79]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Mails, Length: 5572, dtype: object

In [81]:
Y

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Prediction, Length: 5572, dtype: int64

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 42)

In [85]:
X_train.shape

(4457,)

In [87]:
y_train.shape

(4457,)

In [89]:
X_test.shape

(1115,)

In [91]:
feature_extraction = TfidfVectorizer(min_df = 1, stop_words="english", binary=True)
X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Prediction  5572 non-null   int64
 1   Mails       5572 non-null   object
dtypes: int64(1), object(1)
memory usage: 87.2+ KB

In [95]:
y_train = y_train.astype("int")
y_test = y_test.astype("int")

In [97]:
X_train

1978    No I'm in the same boat. Still here at my moms...
3989    (Bank of Granite issues Strong-Buy) EXPLOSIVE ...
3935       They r giving a second chance to rahul dengra.
4078       O i played smash bros  &lt;#&gt;  religiously.
4086    PRIVATE! Your 2003 Account Statement for 07973...
                              ...
3772    I came hostel. I m going to sleep. Plz call me...
5191                               Sorry, I'll call later
5226        Prabha..i'm soryda..realy..frm heart i'm sory
5390                           Nt joking seriously i told
860                   In work now. Going have in few min.
Name: Mails, Length: 4457, dtype: object

In [99]:
print(X_train_features)

  (0, 1371)	0.4658046386365619
  (0, 4416)	0.4528381701109944
  (0, 1706)	0.3431839629173582
  (0, 7415)	0.348722265231364
  (0, 3210)	0.348722265231364
  (0, 4520)	0.4658046386365619
  (1, 1187)	0.26161139982801973
  (1, 3140)	0.3059746053542906
  (1, 3631)	0.2804339696184593
  (1, 6296)	0.269833648032668
  (1, 1533)	0.2015782058421696
  (1, 2661)	0.3059746053542906
  (1, 5005)	0.1937920260229529
  (1, 4292)	0.2953742837684993
  (1, 419)	0.28715203556385105
  (1, 4533)	0.3059746053542906
  (1, 6440)	0.2953742837684993
  (1, 1649)	0.3059746053542906
  (1, 0)	0.2654936554684193
  (2, 3061)	0.44585171875646595
  (2, 5770)	0.3962151014046925
  (2, 1674)	0.35156722029872034
  (2, 5351)	0.5102109014477275
  (2, 2190)	0.5102109014477275
  (3, 5048)	0.4444794309161828
  :	:
  (4451, 5002)	0.36484607066812064
  (4451, 4939)	0.36484607066812064
  (4452, 3085)	0.25923599228241945
  (4452, 5070)	0.3823754823843719
  (4452, 5998)	0.3311324953642251
  (4452, 1781)	0.3311324953642251
  (4452, 1579)	0.3576443319642905
  (4452, 3423)	0.4833413012939851
  (4452, 3402)	0.4536077050510107
  (4453, 4022)	0.5251399912435084
  (4453, 3896)	0.6138307933697734
  (4453, 6102)	0.5894401977366341
  (4454, 3282)	0.31753127203477105
  (4454, 5161)	0.43497582872738466
  (4454, 6109)	0.44743083090000146
  (4454, 5413)	0.40874206042479744
  (4454, 2938)	0.3775064911532845
  (4454, 6108)	0.44743083090000146
  (4455, 3720)	0.5663548747533713
  (4455, 4674)	0.47741741602516974
  (4455, 5819)	0.5321975225970689
  (4455, 6701)	0.40997629646174116
  (4456, 3085)	0.5132022683472269
  (4456, 7301)	0.5938942231507836
  (4456, 4332)	0.6196072009518515

In [101]:
print(X_test_features)

  (0, 1756)	0.31111329907426943
  (0, 2679)	0.3500886226408095
  (0, 2974)	0.34299776014114036
  (0, 3239)	0.34299776014114036
  (0, 3457)	0.3500886226408095
  (0, 3752)	0.1718556592061185
  (0, 4543)	0.38197308370768035
  (0, 6816)	0.4006242977875035
  (0, 7229)	0.2947064107791228
  (1, 1934)	0.22392171769600464
  (1, 1970)	0.2461378627103295
  (1, 2651)	0.3269309971271071
  (1, 3716)	0.3178303138520559
  (1, 4760)	0.29866169283344046
  (1, 5532)	0.33866381848750327
  (1, 5738)	0.25559165628741076
  (1, 5739)	0.35520030142077386
  (1, 5744)	0.35520030142077386
  (1, 5812)	0.22078293973996208
  (1, 6604)	0.19484478334547534
  (1, 6607)	0.27039238853977376
  (2, 305)	0.3520274907931286
  (2, 2707)	0.5381246423289194
  (2, 3835)	0.26760645025649377
  (2, 4106)	0.5644005196977707
  :	:
  (1110, 1533)	0.2553888613819584
  (1110, 1599)	0.27571108916401915
  (1110, 1745)	0.3876535449194833
  (1110, 1869)	0.3876535449194833
  (1110, 2148)	0.301483654608874
  (1110, 2651)	0.3742235014841453
  (1110, 3174)	0.19113154928290435
  (1110, 3363)	0.3742235014841453
  (1110, 4022)	0.191596066847086
  (1110, 4109)	0.1906716083208562
  (1111, 268)	0.3746977741925054
  (1111, 503)	0.47727320057783823
  (1111, 1012)	0.47727320057783823
  (1111, 1459)	0.45505356814989883
  (1111, 2451)	0.33671306166726417
  (1111, 4435)	0.2890894779341821
  (1112, 4362)	0.5790142409011977
  (1112, 6561)	0.6933358898870733
  (1112, 7404)	0.4289846764490662
  (1113, 2362)	1.0
  (1114, 305)	0.3544958704238923
  (1114, 1309)	0.5418979155552348
  (1114, 1408)	0.38742253378806535
  (1114, 4580)	0.5231241609003211
  (1114, 5073)	0.39613661729871547

In [107]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_features, y_train)

LogisticRegression()

In [109]:
prediction_train_data = model.predict(X_train_features)
accuracy_train_data = accuracy_score(y_train, prediction_train_data)

In [111]:
print("Accuarcy on train data: ", accuracy_train_data)

Accuarcy on train data:  0.9672425398249944

In [113]:
prediction_test_data = model.predict(X_test_features)
accuracy_test_data = accuracy_score(y_test, prediction_test_data)

In [115]:
print("Accuarcy on test data: ", accuracy_test_data)

Accuarcy on test data:  0.9533632286995516

In [117]:
# Building predictive system

In [119]:
input_user_mail = ["SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info"]

input_data_features = feature_extraction.transform(input_user_mail)

prediction = model.predict(input_data_features)

if prediction[0] == 1:
    print("This is a ham mail")
else:
    print("This is a spam mail")

This is a spam mail

In [121]:
import pickle
pickle.dump(model, open("logistic_regression.pkl", "wb"))
pickle.dump(feature_extraction, open("feature_extraction.pkl", "wb"))